
'use strict';
const controls=document.querySelector('.tools'),surface=$('webgl'),catalog=document.createElement('section'),relationships=document.createElement('div');
catalog.id='catalog';catalog.hidden=true;catalog.setAttribute('aria-label','Proposed SKU prices');relationships.id='relationships';relationships.setAttribute('aria-label','Selectable relationship sentences');document.querySelector('.board').append(catalog,relationships);
function addButton(id,label,fn){const b=text('button',label,controls);b.id=id;b.onclick=fn;return b}
const pinButton=addButton('pin','Pin selected',()=>pinSelected(true)),unpinButton=addButton('unpin','Unpin selected',()=>pinSelected(false));
let engine=null,THREE=null,webglReady=false,positions=new Map(),lastView='',orbitAngle=.2;
const fallbackRender=render;
function key(id){return (guided?'tour-'+stop:'explore')+':'+id}
function message(s){$('message').textContent=s}
function pinSelected(pin){if(!engine||!selected)return message('Select a concept first.');const n=engine.graphData().nodes.find(n=>n.id===selected);if(!n)return message('Selected relationship cannot be pinned. Select a concept.');if(pin){n.fx=n.x;n.fy=n.y;n.fz=n.z}else{delete n.fx;delete n.fy;delete n.fz}positions.set(key(n.id),{x:n.x,y:n.y,z:n.z,pinned:pin});message((pin?'Pinned: ':'Unpinned: ')+n.label);engine.refresh()}
function updateCatalog(){catalog.hidden=!$('overlay').checked;if(catalog.hidden)return;catalog.replaceChildren();text('p','CURRENT WORLDMAP · separately sourced proposals and estimates, not transcript results.',catalog);for(const n of graph.nodes.filter(n=>n.overlay)){const c=text('article','',catalog,'sku-card');text('h3','SKU '+n.sku.id+' · '+n.label,c);text('strong',n.sku.priceHypothesis,c);text('p','Stage: '+n.sku.status,c);text('p',n.sku.outcome,c);const b=text('button','Inspect price, gate & source',c);b.onclick=()=>inspect(n)}}
function safeTooltip(label){const p=document.createElement('div');p.textContent=label;return p}
function makeSprite(lines,color,size,bg=true){const canvas=document.createElement('canvas');canvas.width=768;canvas.height=Math.max(176,lines.length*44+48);const ctx=canvas.getContext('2d');if(bg){ctx.fillStyle='rgba(7,30,48,.95)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=color;ctx.lineWidth=3;ctx.strokeRect(2,2,canvas.width-4,canvas.height-4);ctx.fillStyle=color;for(const x of[2,canvas.width-20])for(const y of[2,canvas.height-20])ctx.fillRect(x,y,18,18)}ctx.font='500 30px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;lines.forEach((line,i)=>ctx.fillText(line,canvas.width/2,28+i*44+20,canvas.width-40));const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));sprite.scale.set(size,size*canvas.height/canvas.width,1);return sprite}
function nodeObject(n){const group=new THREE.Group(),color=n.id===selected?'#fff4b0':n.overlay?'#8acaff':'#68e2ff';const lines=wrapLabel(n.label,30).split('\n');if(n.sku)lines.push(n.sku.priceHypothesis);if(positions.get(key(n.id))?.pinned)lines.push('PINNED');group.add(makeSprite(lines,color,n.members?.length>1?205:180));if(n.id===selected){const pts=Array.from({length:65},(_,i)=>new THREE.Vector3(Math.cos(i*Math.PI/32)*120,Math.sin(i*Math.PI/32)*120,-20));group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#56dfff',transparent:true,opacity:.6})));}return group}
function refreshScene(){fallbackRender();updateCatalog();if(!webglReady||flat){surface.hidden=true;$('stage').hidden=false;return}
surface.hidden=false;$('stage').hidden=true;let raw=visible();if(!guided&&!collapsed&&selected&&graph.nodes.some(n=>n.id===selected)){const wanted=new Set([selected]);graph.edges.filter(e=>e.from===selected||e.to===selected).forEach(e=>{wanted.add(e.from);wanted.add(e.to)});raw=raw.filter(n=>wanted.has(n.id))}
const groups=new Map;for(const n of raw){const id=!guided&&collapsed?(n.cluster||n.id):n.id;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(n)}
const nodes=[...groups].map(([id,m],i)=>{const n=m.length>1?{id,label:id+' · '+m.length+' concepts',members:m,overlay:m.every(n=>n.overlay)}:{...m[0],members:m};let pos=positions.get(key(id));if(!pos){if(guided)pos={x:(i-(groups.size-1)/2)*300,y:(i%2)*100-50,z:(i%2)*70-35};else if(selected&&!collapsed){pos=id===selected?{x:0,y:0,z:0}:{x:Math.cos(i*2*Math.PI/(groups.size-1))*380,y:Math.sin(i*2*Math.PI/(groups.size-1))*270,z:(i%3-1)*90}}else pos={x:Math.cos(i*2.399)*(280+18*Math.sqrt(i)),y:Math.sin(i*2.399)*(180+15*Math.sqrt(i)),z:((i%3)-1)*110};}return{...n,...pos,...(pos.pinned?{fx:pos.x,fy:pos.y,fz:pos.z}:{})}});
const lookup=new Map;nodes.forEach(n=>n.members.forEach(m=>lookup.set(m.id,n.id)));let edges=guided?graph.edges.filter(e=>graph.tour[stop].edgeIds.includes(e.id)):selected&&!collapsed?graph.edges.filter(e=>e.id===selected||e.from===selected||e.to===selected):graph.edges;
edges=edges.filter(e=>(!e.overlay||$('overlay').checked)&&(!$('status').value||e.status===$('status').value)&&(!$('source').value||e.evidenceIds.some(id=>graph.evidence.find(v=>v.id===id).sourceId===$('source').value)));
const links=edges.filter(e=>lookup.has(e.from)&&lookup.has(e.to)&&lookup.get(e.from)!==lookup.get(e.to)).map(e=>({...e,source:lookup.get(e.from),target:lookup.get(e.to)}));
relationships.replaceChildren();for(const e of links){const sentence=graph.nodes.find(n=>n.id===e.from).label+' '+e.label+' '+graph.nodes.find(n=>n.id===e.to).label;const b=text('button',sentence,relationships);b.onclick=()=>inspect(graph.edges.find(x=>x.id===e.id))}
engine.width(surface.clientWidth).height(surface.clientHeight).graphData({nodes,links});
const view=(guided?'tour-'+stop:'explore')+':'+collapsed+':'+(selected||'');if(view!==lastView){lastView=view;requestAnimationFrame(()=>engine.zoomToFit(400,100))}pinButton.disabled=!nodes.some(n=>n.id===selected);unpinButton.disabled=pinButton.disabled;
message(nodes.length?'WebGL 3D ready · '+nodes.length+' concept panels · '+links.length+' labeled paths. Drag a panel to move and pin it.':'No concepts match these filters. Clear filters to continue.');
}
render=refreshScene;
const inspectOriginal=inspect;inspect=function(x){inspectOriginal(x);if(x.sku){text('h3','Proposed price',$('inspector'));text('p',x.sku.priceHypothesis,$('inspector'));text('h3','Current roadmap stage',$('inspector'));text('p',x.sku.status,$('inspector'));text('h3','Validation gate',$('inspector'));text('p',x.sku.validationGate,$('inspector'));text('p','Separately sourced current-worldmap proposal; not transcript evidence or a realized business result.',$('inspector'),'muted')}};
$('dim').onclick=()=>{flat=!flat;$('dim').textContent=flat?'WebGL 3D':'Readable 2D';render()};$('reset').onclick=()=>{if(engine&&!flat){selected='';lastView='';engine.cameraPosition({x:0,y:100,z:1400},{x:0,y:0,z:0},350);render()}else reset()};addButton('reset-layout','Reset layout',()=>{positions.clear();selected='';lastView='';render();message('Layout reset. All session pins cleared.')});
$('left').onclick=()=>orbit(-.25);$('right').onclick=()=>orbit(.25);function orbit(delta){if(!engine||flat){yaw+=delta;fallbackRender();return}orbitAngle+=delta;engine.cameraPosition({x:Math.sin(orbitAngle)*1300,y:100,z:Math.cos(orbitAngle)*1300},{x:0,y:0,z:0},350)}
$('zin').onclick=()=>scaleCamera(.85);$('zout').onclick=()=>scaleCamera(1.15);function scaleCamera(k){if(!engine||flat){zoom=Math.max(.3,Math.min(3,zoom/k));fallbackRender();return}const p=engine.cameraPosition();engine.cameraPosition({x:p.x*k,y:p.y*k,z:p.z*k},undefined,300)}
const loadedOriginal=load;load=function(g){positions.clear();lastView='';loadedOriginal(g);render()};
message('Loading pinned WebGL packages… Readable 2D remains available.');
try{
[THREE]=await Promise.all([import('three')]);const{default:ForceGraph3D}=await import('https://esm.sh/3d-force-graph@1.80.1?external=three');
surface.hidden=false;engine=new ForceGraph3D(surface,{controlType:'orbit',rendererConfig:{antialias:true,alpha:true}}).backgroundColor('#061527').showNavInfo(false).cooldownTicks(0).warmupTicks(0).nodeThreeObject(nodeObject).nodeLabel(n=>safeTooltip(n.label)).linkLabel(e=>safeTooltip(e.label)).linkColor(e=>e.id===selected?'#ffe99a':'#53bfe8').linkWidth(e=>e.id===selected?2:1).linkOpacity(.75).linkDirectionalArrowLength(8).linkDirectionalArrowRelPos(.7).linkThreeObjectExtend(true).linkThreeObject(e=>makeSprite(wrapLabel(e.label,38).split('\n'),'#c5edff',140,false)).linkPositionUpdate((o,{start,end})=>{o.position.set((start.x+end.x)/2,(start.y+end.y)/2,(start.z+end.z)/2)}).onNodeClick(n=>{if(n.members.length>1){collapsed=false;selected='';$('collapse').textContent='Collapse clusters';render()}else inspect(graph.nodes.find(x=>x.id===n.id))}).onLinkClick(e=>inspect(graph.edges.find(x=>x.id===e.id))).onNodeDragEnd(n=>{n.fx=n.x;n.fy=n.y;n.fz=n.z;positions.set(key(n.id),{x:n.x,y:n.y,z:n.z,pinned:true});message('Moved and pinned: '+n.label);engine.refresh()});
const grid=new THREE.GridHelper(1600,32,'#245c78','#16394e');grid.position.y=-420;engine.scene().add(grid);
const board=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1400,900,12)),new THREE.LineBasicMaterial({color:'#3cb9e0',transparent:true,opacity:.32}));board.position.z=-300;engine.scene().add(board);
engine.renderer().domElement.setAttribute('aria-label','WebGL concept map; use concept buttons for keyboard navigation');engine.renderer().domElement.setAttribute('tabindex','0');engine.renderer().domElement.addEventListener('webglcontextlost',()=>{webglReady=false;render();message('WebGL context lost. Readable 2D is active. Reload to retry 3D.')});
webglReady=true;new ResizeObserver(()=>{if(!surface.hidden)engine.width(surface.clientWidth).height(surface.clientHeight)}).observe(surface);render();
}catch(error){webglReady=false;flat=true;$('dim').textContent='WebGL unavailable';render();message('WebGL could not load: '+error.message+'. Readable 2D is active.')}
